name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Robot Framework tests
    - name: Run Robot Framework tests
      run: |
        robot --outputdir results tests/

    # Step 5: Upload test results as artifacts
    - name: Upload Robot Reports
      uses: actions/upload-artifact@v4
      with:
        name: robot-report
        path: results/
